version: "3"

services: 
    appweb:
        container_name: exampleapp
        restart: always
        build: .
        ports:
            - "5000:3000"
        links: 
            - mongo
        volumes: 
            - .:/usr/src/app
    mongo:
        container_name: mymongodtbs
        image: mongo
        ports: 
            - "27018:27017"
        logging:
            driver: none